---
title: "Exploring World Bank Data"
author: "Kejing Li"
output: github_document
---

## Load necessary libraries

```{r}
library(tidyverse)
```

## Write a function to import the data files

```{r}
read_and_tidy <- function(path) {
  data <- read.csv(path, skip = 4) %>%
    filter("Indicator Code" %in% c( "IC.FRM.FEMO.ZS",
                                    "IC.FRM.FEMM.ZS",
                                    "IC.REG.PROC.FE",
                                    "TX.VAL.TECH.MF.ZS") ) %>%
    pivot_longer(-c("Country Name",
                    "Country Code", 
                    "Indicator Name", 
                    "Indicator Code"),
                 names_to = "Year",
                 values_to = "Value") %>%
    pivot_wider(names_from = "Indicator Code",
                values_from = "Value") %>%
  
  return(data)     
}
```

## Import the data

```{r}
data1 <- read.csv("data_world_bank/API_ABW_DS2_en_csv_v2_10592147.csv", skip=3)

data1%>%
  select(-Country.Code, -Indicator.Name)%>%
  filter(Indicator.Code %in% c("IC.FRM.FEMO.ZS",
                                    "IC.FRM.FEMM.ZS",
                                    "IC.REG.PROC.FE",
                                    "TX.VAL.TECH.MF.ZS"))%>%
     
    pivot_longer(-c("Country.Name",
                    "Indicator.Code"),
                 names_to = "Year",
                 values_to = "Value",
                 names_prefix = "X") %>%
    pivot_wider(names_from = "Indicator.Code",
                values_from = "Value") %>%
    rename(hitech_export = TX.VAL.TECH.MF.ZS,
           female_register_procedure = IC.REG.PROC.FE,
           female_ownership_participation = IC.FRM.FEMO.ZS,
           female_top_management = IC.FRM.FEMM.ZS) %>%
    
    
  
  

```



```{r}
directory <- dir(path = "data_world_bank", full.names = TRUE)
data <- vector("list", length(directory))
for (i in seq_along(directory)){
  data[[i]] <-  read_and_tidy(directory[[1]])
}

bind_rows(data)
```

## Explore the data
```{r}
data
```


## Session info

```{r}
devtools::session_info()
```


